# Use official Java 21 runtime
FROM openjdk:21-jdk-slim

# Set working directory inside container
WORKDIR /app

# Copy project files
COPY . .

# Build with Gradle (skip tests for faster deploy)
RUN ./gradlew build -x test

# Run the bootJar generated by build.gradle
CMD ["java", "-jar", "build/libs/app.jar"]
